### ISSUE TITLE
Examples for java do not seem to work

### ISSUE THREAD

**Issue by zaza** [PractiTest/pt-api-examples#9]
Just starting with PraciTest API so maybe I missed something obvious, but I tried both java examples from this repository and they both return the same response:

`{
    "errors": [
        {
            "status": 401,
            "title": "Invalid api_token parameter"
        }
    ]
}`

I updated GetWithResponse.DEVELOPER_EMAIL and .API_TOKEN with my email and my Personal API Token. Did the same with project.properties file in the other examples project. All to no avail. What did I miss?

**Comment by zaza** [comment]
I think I found it. My account is hosted in EU so I should use a different BASE_URL. The [doc says](https://www.practitest.com/api-v2/#base-url) it should be https://eu1-prod.practitest.app but the correct value is https://eu1-prod-api.practitest.app

**Comment by stask** [comment]
Thanks @zaza, we'll fix the documentation.
